
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-mister-cocktail_development



  <<: *default
  database: rails-mister-cocktail_test


production:
  <<: *default
  database: rails-mister-cocktail_production
  username: rails-mister-cocktail
  password: <%= ENV['RAILS-MISTER-COCKTAIL_DATABASE_PASSWORD'] %>

production:
  <<: *default
  url: <%= ENV['POSTGRESQL_ADDON_URI'] %>
